import type { ForwardingRule, HealthCheck, StickySessions } from './lb.types';

export interface RenderTarget {
  serverId: string;
  name: string;
  address: string;
}

export interface RenderInput {
  id: string;
  algorithm: 'round_robin' | 'least_conn';
  rules: ForwardingRule[];
  healthCheck: HealthCheck;
  sticky: StickySessions | null;
  redirectHttpToHttps: boolean;
  proxyProtocol: boolean;
  targets: RenderTarget[];
}

/**
 * Renders haproxy.cfg for a load balancer. One frontend per entry port, one backend per
 * rule. HTTPS terminates on the node with the certificate at /etc/haproxy/certs/<id>.pem;
 * Let's Encrypt challenges are routed to certbot on 127.0.0.1:8402. Pure function so it is
 * unit testable and identical on every node.
 */
export function renderHaproxyConfig(lb: RenderInput): string {
  const hc = lb.healthCheck;
  const balance = lb.algorithm === 'least_conn' ? 'leastconn' : 'roundrobin';
  const hasHttps = lb.rules.some((r) => r.entryProtocol === 'https');
  const lines: string[] = [
    '# Generated by pgcloud. Edits are overwritten on the next change.',
    'global',
    '  log /dev/log local0',
    '  maxconn 20000',
    '  stats socket /run/haproxy/admin.sock mode 660 level admin',
    '  tune.ssl.default-dh-param 2048',
    '  ssl-default-bind-options ssl-min-ver TLSv1.2',
    '',
    'defaults',
    '  log global',
    '  option dontlognull',
    '  timeout connect 5s',
    '  timeout client 60s',
    '  timeout server 60s',
    '  timeout http-request 10s',
    `  default-server inter ${hc.intervalSeconds}s fall ${hc.unhealthyThreshold} rise ${hc.healthyThreshold}`,
    '',
    'listen stats',
    '  bind 127.0.0.1:8404',
    '  mode http',
    '  stats enable',
    '  stats uri /',
    '',
    'backend acme',
    '  mode http',
    '  server certbot 127.0.0.1:8402',
    '',
  ];
  lb.rules.forEach((r, i) => {
    const mode = r.entryProtocol === 'tcp' ? 'tcp' : 'http';
    lines.push(`frontend fe_${r.entryPort}`);
    lines.push(`  bind *:${r.entryPort}${r.entryProtocol === 'https' ? ` ssl crt /etc/haproxy/certs/${safe(r.certificateId ?? 'none')}.pem alpn h2,http/1.1` : ''}`);
    lines.push(`  mode ${mode}`);
    if (mode === 'http') {
      lines.push('  option forwardfor');
      lines.push('  http-request set-header X-Forwarded-Proto %[ssl_fc,iif(https,http)]');
      lines.push('  acl acme path_beg /.well-known/acme-challenge/');
      lines.push('  use_backend acme if acme');
      if (lb.redirectHttpToHttps && r.entryProtocol === 'http' && hasHttps) lines.push('  http-request redirect scheme https code 301 unless { ssl_fc } || acme');
    }
    lines.push(`  default_backend be_${i}`);
    lines.push('');
    lines.push(`backend be_${i}`);
    lines.push(`  mode ${r.targetProtocol === 'tcp' || mode === 'tcp' ? 'tcp' : 'http'}`);
    lines.push(`  balance ${balance}`);
    if (hc.protocol === 'http' && mode === 'http') lines.push(`  option httpchk GET ${hc.path || '/'}`);
    if (lb.sticky?.type === 'cookie' && mode === 'http') lines.push(`  cookie ${lb.sticky.cookieName || 'PGCLOUDLB'} insert indirect nocache${lb.sticky.ttlSeconds ? ` maxidle ${lb.sticky.ttlSeconds}s` : ''}`);
    for (const t of lb.targets) {
      lines.push(`  server srv_${t.serverId} ${t.address}:${r.targetPort} check port ${hc.port}${lb.sticky?.type === 'cookie' && mode === 'http' ? ` cookie ${t.serverId}` : ''}${lb.proxyProtocol ? ' send-proxy' : ''}`);
    }
    if (!lb.targets.length) lines.push('  # no targets yet');
    lines.push('');
  });
  return lines.join('\n');
}

/** keepalived.conf: every node runs VRRP for the VIP; node 0 is the preferred master. */
export function renderKeepalivedConfig(o: { lbId: string; index: number; vip: string; prefix: number; iface?: string }): string {
  const vrid = (hash(o.lbId) % 254) + 1;
  return [
    'vrrp_script chk_haproxy {',
    '  script "/usr/bin/pgrep -x haproxy"',
    '  interval 2',
    '  weight -60',
    '}',
    'vrrp_instance VI_pgcloud {',
    `  state ${o.index === 0 ? 'MASTER' : 'BACKUP'}`,
    `  interface ${o.iface ?? 'eth0'}`,
    `  virtual_router_id ${vrid}`,
    `  priority ${150 - o.index * 40}`,
    '  advert_int 1',
    '  nopreempt',
    '  authentication { auth_type PASS auth_pass pgcloud }',
    `  virtual_ipaddress { ${o.vip}/${o.prefix} }`,
    '  track_script { chk_haproxy }',
    '}',
    '',
  ].join('\n');
}

function safe(s: string) {
  return s.replace(/[^a-zA-Z0-9_-]/g, '');
}

function hash(s: string) {
  let h = 0;
  for (const c of s) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return h;
}
